#==============================================================================
# Production Environment Configuration
#==============================================================================
# Optimized Docker Compose setup for Laravel production deployment with:
# - Nginx with compiled frontend assets
# - PHP-FPM with health checks
# - Queue worker for background jobs
# - MySQL database with health monitoring
# - Redis cache
# - Persistent volumes for data storage
#==============================================================================

services:
  #----------------------------------------------------------------------------
  # Nginx Web Server
  #----------------------------------------------------------------------------
  # Serves compiled static assets and proxies PHP requests
  web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - laravel-storage-production:/var/www/storage:ro # Read-only access
    networks:
      - laravel-production
    depends_on:
      php-fpm:
        condition: service_healthy

  #----------------------------------------------------------------------------
  # PHP-FPM Application Server
  #----------------------------------------------------------------------------
  # Processes PHP requests with production optimizations
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    # Entrypoint runs as root to set permissions, then PHP-FPM workers run as www-data
    # user: "www-data:www-data" # Commented out to allow entrypoint to run as root
    env_file:
      - .env
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      mysql:
        condition: service_healthy

  #----------------------------------------------------------------------------
  # Queue Worker
  #----------------------------------------------------------------------------
  # Processes background jobs from the queue
  worker:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    user: "www-data:www-data"
    entrypoint: []
    command: >
      sh -c "
      cd /var/www &&
      php artisan config:clear &&
      php artisan queue:work --sleep=3 --tries=3 --max-time=3600 --verbose
      "
    env_file:
      - .env
    volumes:
      - laravel-storage-production:/var/www/storage
    networks:
      - laravel-production
    depends_on:
      mysql:
        condition: service_healthy
      php-fpm:
        condition: service_healthy

  #----------------------------------------------------------------------------
  # MySQL Database
  #----------------------------------------------------------------------------
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "${MYSQL_EXTERNAL_PORT:-3307}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: production
      SERVICE_NAME: mysql
    volumes:
      - mysql-data-production:/var/lib/mysql
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 30s

  #----------------------------------------------------------------------------
  # PostgreSQL Database (Alternative)
  #----------------------------------------------------------------------------
  # Uncomment if using PostgreSQL instead of MySQL
  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   user: postgres
  #   ports:
  #     - "${POSTGRES_PORT:-5432}:5432"
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DATABASE:-app}
  #     POSTGRES_USER: ${POSTGRES_USERNAME:-laravel}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
  #   volumes:
  #     - postgres-data-production:/var/lib/postgresql/data
  #   networks:
  #     - laravel-production
  #   healthcheck:
  #     test: ["CMD", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  #----------------------------------------------------------------------------
  # Redis Cache & Session Store
  #----------------------------------------------------------------------------
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

#==============================================================================
# Networks
#==============================================================================
# Isolated network for all production services
networks:
  laravel-production:
    driver: bridge

#==============================================================================
# Volumes
#==============================================================================
# Persistent storage for production data
volumes:
  mysql-data-production:
    driver: local
  # postgres-data-production:
  #   driver: local
  laravel-storage-production:
    driver: local
