#==============================================================================
# Development Environment Configuration
#==============================================================================
# This compose file sets up a complete Laravel development environment with:
# - Nginx web server with live reload
# - PHP-FPM with Xdebug support
# - MySQL database
# - Redis cache
# - Workspace container for running commands (Composer, Artisan, NPM)
#==============================================================================

services:
  #----------------------------------------------------------------------------
  # Nginx Web Server
  #----------------------------------------------------------------------------
  # Serves static files and proxies PHP requests to php-fpm
  web:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    environment:
      NGINX_HOST: hpvtcrm.local
    ports:
      - "80:80"
    volumes:
      - ./:/var/www # Live code updates
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Custom Nginx config
    networks:
      - hpvtcrm-dev
    depends_on:
      php-fpm:
        condition: service_started

  #----------------------------------------------------------------------------
  # Workspace Container
  #----------------------------------------------------------------------------
  # Interactive container for running commands (Composer, Artisan, NPM, etc.)
  workspace:
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    ports:
      - "${VITE_PORT:-5173}:5173" # Vite dev server for hot module replacement
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - hpvtcrm-dev

  #----------------------------------------------------------------------------
  # PHP-FPM
  #----------------------------------------------------------------------------
  # Processes PHP requests with Xdebug enabled for development
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        XDEBUG_ENABLED: ${XDEBUG_ENABLED:-true}
        XDEBUG_MODE: develop,coverage,debug,profile
        XDEBUG_HOST: ${XDEBUG_HOST:-host.docker.internal}
        XDEBUG_IDE_KEY: ${XDEBUG_IDE_KEY:-DOCKER}
        XDEBUG_LOG: /dev/stdout
        XDEBUG_LOG_LEVEL: 0
    env_file:
      - .env
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www # Live code updates
    networks:
      - hpvtcrm-dev
    depends_on:
      mysql:
        condition: service_healthy

  #----------------------------------------------------------------------------
  # MySQL Database
  #----------------------------------------------------------------------------
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data_development:/var/lib/mysql
    networks:
      - hpvtcrm-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  #----------------------------------------------------------------------------
  # Redis Cache
  #----------------------------------------------------------------------------
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - hpvtcrm-dev

  worker:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
    restart: on-failure
    entrypoint: /bin/sh
    command:
      - -c
      - |
        cd /var/www
        sleep 10
        echo "Starting scheduler and queue worker..."
        while true; do php artisan schedule:run; sleep 60; done &
        php artisan queue:work --sleep=3 --tries=3 --timeout=60 --verbose
    env_file:
      - .env
    volumes:
      - ./:/var/www
    networks:
      - hpvtcrm-dev
    depends_on:
      mysql:
        condition: service_healthy

#==============================================================================
# Networks
#==============================================================================
networks:
  hpvtcrm-dev:
    driver: bridge

#==============================================================================
# Volumes
#==============================================================================
volumes:
  mysql_data_development:
    driver: local
